/**
 * Seed script — populates MongoDB with real project data fetched from Monday.com via MCP.
 * Run with: npx tsx scripts/seedFromMonday.ts
 *
 * Data sources:
 *   - MA-004 (7321609006): project name, number, status, budget hours
 *   - MA-003 (8874793711): team members (BIM/MEP/Modeller), ACC URL
 *   - ma003lookup.json:    pre-extracted MA-003 data (generated by MCP session)
 */

import path from 'path'
import fs from 'fs'
import mongoose from 'mongoose'

// ── Env ────────────────────────────────────────────────────────────────────

const MONGODB_URI = process.env.MONGODB_URI
if (!MONGODB_URI) { console.error('MONGODB_URI not set'); process.exit(1) }

const MA004_BOARD_ID  = '7321609006'
const MA004_BOARD_URL = 'https://easybim-company.monday.com/boards/7321609006'

// ── Status mapping ─────────────────────────────────────────────────────────

type ProjectStatus = 'Working on it' | 'On Hold' | 'Not Started' | 'Done' | 'Stuck'

function mapStatus(raw: string): ProjectStatus | null {
  if (raw === 'Working on it')              return 'Working on it'
  if (raw === 'On Hold')                    return 'On Hold'
  if (raw === 'Not Started')                return 'Not Started'
  if (raw === 'Finished' || raw === 'DONE') return 'Done'
  if (raw === 'Stuck' || raw === 'Declined') return 'Stuck'
  return null
}

// ── Raw MA-004 data ────────────────────────────────────────────────────────

interface MA004Row {
  num:    string
  name:   string
  rawStatus: string
  budget: number
  ma004Id: string
  ma003Id: string | null
}

const MA004_PROJECTS: MA004Row[] = [
  { num:'22117', name:'ספריית יהוד',                                          rawStatus:'On Hold',       budget:168.55, ma004Id:'7321609192',  ma003Id:'8874964018'  },
  { num:'22101', name:'בר עקיבא - ליווי BIM משרדי',                          rawStatus:'Working on it', budget:480,    ma004Id:'8817956796',  ma003Id:null          },
  { num:'22110', name:'יפו 167 - הגדלת שכ"ט',                                rawStatus:'On Hold',       budget:233.33, ma004Id:'9308550679',  ma003Id:null          },
  { num:'22116', name:'זכרון 7, ת"א',                                          rawStatus:'On Hold',       budget:133.33, ma004Id:'7321609219',  ma003Id:'8874964094'  },
  { num:'22121', name:'22121-2051 Katamon',                                    rawStatus:'On Hold',       budget:192.83, ma004Id:'7321609230',  ma003Id:'9013355876'  },
  { num:'22120', name:'לודן צפון - ליווי BIM משרדי',                         rawStatus:'Working on it', budget:800.33, ma004Id:'11118544144', ma003Id:null          },
  { num:'22125', name:'ארנה הרצליה',                                          rawStatus:'Working on it', budget:633.33, ma004Id:'7321609251',  ma003Id:'8874964376'  },
  { num:'22126', name:'אלתרמן 2-4',                                            rawStatus:'On Hold',       budget:244.45, ma004Id:'7321609258',  ma003Id:'8874964442'  },
  { num:'22127', name:'מרכז רפואי אופקים',                                    rawStatus:'Not Started',   budget:278.33, ma004Id:'7321609269',  ma003Id:null          },
  { num:'22158', name:'הררי - ליווי BIM משרדי',                              rawStatus:'Working on it', budget:392,    ma004Id:'8141982343',  ma003Id:null          },
  { num:'22128', name:'מבנה פגיה שיבא',                                      rawStatus:'Working on it', budget:2342.83,ma004Id:'7321609273',  ma003Id:'8874964499'  },
  { num:'22129', name:'פרויקט מול תבור- נוף הגליל',                          rawStatus:'Working on it', budget:765.77, ma004Id:'7321609280',  ma003Id:'8874964568'  },
  { num:'22130', name:'ארנה אשדוד',                                            rawStatus:'Working on it', budget:797.93, ma004Id:'7321609290',  ma003Id:'8874964663'  },
  { num:'22176', name:'בן סרוק 10-12 ת"א',                                    rawStatus:'On Hold',       budget:333.33, ma004Id:'9013585336',  ma003Id:'9020403414'  },
  { num:'22131', name:'נתצים בית שמש',                                        rawStatus:'Working on it', budget:794.33, ma004Id:'7321609242',  ma003Id:'8874964748'  },
  { num:'22162', name:'קבוצת בראל - ליווי בים',                              rawStatus:'Working on it', budget:25,     ma004Id:'8273985250',  ma003Id:null          },
  { num:'22203', name:'אלעזר נתיבות',                                          rawStatus:'Working on it', budget:333.33, ma004Id:'11032880473', ma003Id:'11234390323' },
  { num:'22136', name:'הרצל זוטא',                                            rawStatus:'On Hold',       budget:313.02, ma004Id:'7321609336',  ma003Id:'8874964897'  },
  { num:'22206', name:'אכסנייה לנוער באשקלון',                               rawStatus:'Working on it', budget:666.67, ma004Id:'11159875003', ma003Id:'11234377209' },
  { num:'22138', name:'פארק קיסריה - מלון גולף ריזורט',                     rawStatus:'Working on it', budget:1660,   ma004Id:'7321609222',  ma003Id:'8874963601'  },
  { num:'22141', name:'הרחבת שבעה כוכבים-דיור מוגן הרצליה',                 rawStatus:'Working on it', budget:780.32, ma004Id:'7321609271',  ma003Id:'8874963675'  },
  { num:'22144', name:'מתחם בן גוריון הוד השרון',                            rawStatus:'Working on it', budget:897.79, ma004Id:'7321609288',  ma003Id:'8874963904'  },
  { num:'22145', name:'חבצלת השרון, מגרש 207',                               rawStatus:'Working on it', budget:264.13, ma004Id:'7321609293',  ma003Id:'8874963982'  },
  { num:'22146', name:'שטמפפר פ"ת',                                          rawStatus:'On Hold',       budget:602.9,  ma004Id:'7321609303',  ma003Id:'8874964090'  },
  { num:'22147', name:'חטיבת אלתא, מיבנה הדר',                               rawStatus:'On Hold',       budget:133.33, ma004Id:'7638919114',  ma003Id:'8874964159'  },
  { num:'22150', name:'פרשקובסקי - תמ"ל 3003 רחובות',                       rawStatus:'On Hold',       budget:1000,   ma004Id:'7731468697',  ma003Id:'8874964370'  },
  { num:'22151', name:'גיבורי ישראל נתניה',                                   rawStatus:'On Hold',       budget:1875.81,ma004Id:'7731802912',  ma003Id:'8874964434'  },
  { num:'22156', name:'לייף סנטר - הר חומה',                                  rawStatus:'Working on it', budget:1361.67,ma004Id:'8008307816',  ma003Id:'8874964729'  },
  { num:'22157', name:'מגרש 16 נשר',                                          rawStatus:'Working on it', budget:882.67, ma004Id:'8112336476',  ma003Id:'8874964835'  },
  { num:'22159', name:'העלייה השנייה 51-53 הרצליה',                          rawStatus:'Working on it', budget:300.5,  ma004Id:'8142042298',  ma003Id:'8874964892'  },
  { num:'22163', name:'מנהרת תשתיות ציר הנופש',                              rawStatus:'Working on it', budget:363.47, ma004Id:'8312346215',  ma003Id:'8874963583'  },
  { num:'22164', name:'מתחם יוספטל קרית ים',                                  rawStatus:'Working on it', budget:3230,   ma004Id:'8354216801',  ma003Id:'8874963653'  },
  { num:'22165', name:'מתחם גניש אור יהודה',                                  rawStatus:'Working on it', budget:1183.7, ma004Id:'8460723620',  ma003Id:'8874963725'  },
  { num:'22168', name:'מגרש 14 הכרם עכו',                                    rawStatus:'Working on it', budget:533.33, ma004Id:'8561077373',  ma003Id:'8874963863'  },
  { num:'22169', name:'אס גי אס גיתם',                                       rawStatus:'Working on it', budget:1526.67,ma004Id:'8613924954',  ma003Id:'10059248352' },
  { num:'22170', name:'מגדל שער גילה',                                        rawStatus:'On Hold',       budget:200,    ma004Id:'8628048432',  ma003Id:'8874963931'  },
  { num:'22171', name:'נס ציונה צפון מזרח מגרש 107',                         rawStatus:'Not Started',   budget:666.67, ma004Id:'8819099571',  ma003Id:'8874963800'  },
  { num:'22173', name:'שדרות טובים 1-5 ר"ג',                                 rawStatus:'Working on it', budget:244.47, ma004Id:'8838872452',  ma003Id:'8874964010'  },
  { num:'22174', name:'הבבא סאלי 105',                                        rawStatus:'Working on it', budget:317.36, ma004Id:'8887651103',  ma003Id:'8892796540'  },
  { num:'22175', name:'המהר"ל מפראג 14',                                     rawStatus:'Working on it', budget:232.34, ma004Id:'8887651168',  ma003Id:'8892796298'  },
  { num:'22178', name:'ויצמן 18, רמת השרון',                                  rawStatus:'Working on it', budget:272.33, ma004Id:'9309228777',  ma003Id:'9326967191'  },
  { num:'22179', name:'גני אז"ר - כפר אז"ר',                                rawStatus:'Working on it', budget:653.87, ma004Id:'9426261973',  ma003Id:'9426307961'  },
  { num:'22180', name:'מתחם 3208 שדה דב',                                    rawStatus:'Working on it', budget:986.67, ma004Id:'9430986713',  ma003Id:'9449346542'  },
  { num:'22181', name:'מטרו אלמנטים תפועליים',                               rawStatus:'Working on it', budget:770,    ma004Id:'9441573345',  ma003Id:'9449346908'  },
  { num:'22182', name:'שרבט קרית אתא',                                        rawStatus:'Working on it', budget:610.63, ma004Id:'9576853831',  ma003Id:'9580593051'  },
  { num:'22183', name:'לוחמי גליפולי 58 גליפולי 56 הזוהר 9-11',             rawStatus:'Working on it', budget:167,    ma004Id:'9599551956',  ma003Id:'9600050492'  },
  { num:'22184', name:'מבנה אינטגרציה',                                       rawStatus:'Working on it', budget:150,    ma004Id:'9687536073',  ma003Id:'9692818157'  },
  { num:'22185', name:'קהילת ציון 13-19 הרצליה',                             rawStatus:'Working on it', budget:570.02, ma004Id:'9744883282',  ma003Id:'9745603848'  },
  { num:'22186', name:'אפטאון',                                               rawStatus:'Working on it', budget:1985,   ma004Id:'9857672025',  ma003Id:'9868533937'  },
  { num:'22187', name:"ז'אן זורס חולון",                                      rawStatus:'Working on it', budget:476.67, ma004Id:'9867154784',  ma003Id:'9868615171'  },
  { num:'22188', name:'תל השומר דרום - מגרשים 109-111',                      rawStatus:'Working on it', budget:602.4,  ma004Id:'9898650028',  ma003Id:'9897760649'  },
  { num:'22189', name:'פרויקט סלע בינוי 105-108',                            rawStatus:'Working on it', budget:794.89, ma004Id:'9898650340',  ma003Id:'9897760878'  },
  { num:'22190', name:'מתחם רקפת',                                            rawStatus:'Not Started',   budget:66.67,  ma004Id:'9898597554',  ma003Id:'9907795086'  },
  { num:'22191', name:'ההסתדרות צפון',                                        rawStatus:'Working on it', budget:1483.33,ma004Id:'18072454496', ma003Id:'18188176845' },
  { num:'22192', name:'דוניץ אלעד - הצעירים רמה"ש',                          rawStatus:'Working on it', budget:883.33, ma004Id:'18188049280', ma003Id:'18189122582' },
  { num:'22193', name:'משרדי אלמוג נס ציונה - ניהול מודל URS/BIM ותאום מערכות', rawStatus:'Working on it', budget:166.67, ma004Id:'18326189184', ma003Id:'10846640001' },
  { num:'22194', name:'אשדוד_האומן 12-14',                                    rawStatus:'On Hold',       budget:776.67, ma004Id:'10523819501', ma003Id:'18371349474' },
  { num:'22195', name:'אחוזת הרצליה',                                         rawStatus:'Not Started',   budget:1283.33,ma004Id:'10563311659', ma003Id:'18380160621' },
  { num:'22196', name:'מבנה אינטגרציה מידול אינסטלציה',                      rawStatus:'Working on it', budget:8,      ma004Id:'10572881414', ma003Id:'9692818157'  },
  { num:'22197', name:"בית ספר על יסודי ברח' ציטלין",                        rawStatus:'Working on it', budget:623.33, ma004Id:'10573468638', ma003Id:'18380851629' },
  { num:'22198', name:'חדרה 1-3 ת"א',                                         rawStatus:'Working on it', budget:219.55, ma004Id:'10575807489', ma003Id:'18380851664' },
  { num:'22199', name:'פרויקט תל גיבורים,חולון',                             rawStatus:'Working on it', budget:1586.74,ma004Id:'10603197694', ma003Id:'18386120419' },
  { num:'22200', name:'מסילות באר שבע דימונה',                               rawStatus:'Working on it', budget:400,    ma004Id:'10664107400', ma003Id:'10664106449' },
  { num:'22201', name:'טרומפלדור 50-54 פ"ת - ניהול מודל ותיאום מערכות',    rawStatus:'Working on it', budget:333.33, ma004Id:'10879962995', ma003Id:'10885040841' },
  { num:'22204', name:'ביה"ס משה שרת',                                       rawStatus:'Working on it', budget:138.68, ma004Id:'11098186911', ma003Id:'11234379388' },
  { num:'22205', name:'המרי גבעתיים',                                         rawStatus:'Working on it', budget:497.89, ma004Id:'11159887488', ma003Id:'11170722093' },
  { num:'22207', name:'הרחבת היישוב בת חפר',                                  rawStatus:'Working on it', budget:250,    ma004Id:'11160045851', ma003Id:'11183697081' },
  { num:'22208', name:'מרכז קדמא',                                            rawStatus:'Working on it', budget:166.67, ma004Id:'11184689541', ma003Id:'11197867628' },
  { num:'22208-2', name:'קדמא - מידול חשמל',                                rawStatus:'Working on it', budget:47.5,   ma004Id:'11621192172', ma003Id:null          },
  { num:'22209', name:'אכסניית אנ"א עין גדי',                                rawStatus:'Working on it', budget:33.33,  ma004Id:'11195417089', ma003Id:'11186678688' },
  { num:'22210', name:'לב הבקעה - מגרש 13',                                  rawStatus:'Working on it', budget:466.67, ma004Id:'11217479155', ma003Id:'11245677244' },
  { num:'22211', name:'רכסים',                                                rawStatus:'Working on it', budget:739,    ma004Id:'11234318678', ma003Id:'11235292052' },
  { num:'22212', name:'מתחם הבילויים - 46-60 ר"ג',                          rawStatus:'Not Started',   budget:733.33, ma004Id:'11258926077', ma003Id:'11278912491' },
  { num:'22213', name:'בית מד"א - הרצליה',                                   rawStatus:'Not Started',   budget:597,    ma004Id:'11283062569', ma003Id:'11293004120' },
  { num:'22214', name:'מגרש 409 - קמפוס עירוני',                             rawStatus:'Working on it', budget:692,    ma004Id:'11285061071', ma003Id:'11303141403' },
  { num:'22215', name:'חירייה מבנה רב-תכליתי',                               rawStatus:'Working on it', budget:333.33, ma004Id:'11293829666', ma003Id:'11293840267' },
  { num:'22216', name:'מבנה 260',                                              rawStatus:'Working on it', budget:200,    ma004Id:'11293824194', ma003Id:'11293873327' },
  { num:'22217', name:'בריכה אולימפית - מרכז הספורט הלאומי',                rawStatus:'Working on it', budget:666.67, ma004Id:'11293970433', ma003Id:'11217506460' },
  { num:'22218', name:'קרית אתא מגרשים 75-77',                               rawStatus:'Working on it', budget:903.33, ma004Id:'11303030097', ma003Id:'11313310892' },
  { num:'22219', name:'הרצל 50-56 פ"ת',                                      rawStatus:'Working on it', budget:379.51, ma004Id:'11339881549', ma003Id:'11341168122' },
  { num:'22220', name:'חוצות המפרץ ניהול BIM',                               rawStatus:'Working on it', budget:50,     ma004Id:'11470578566', ma003Id:'11499361476' },
  { num:'22221', name:'התשב"צ תל אביב',                                      rawStatus:'Working on it', budget:1120,   ma004Id:'11535155657', ma003Id:'11544522509' },
  { num:'22222', name:'אכסניית אנ"א כרי דשא',                               rawStatus:'Working on it', budget:229.17, ma004Id:'11569263845', ma003Id:'11620950994' },
  { num:'22223', name:'עין יהב 3-13 חולון',                                  rawStatus:'Working on it', budget:821,    ma004Id:'11569248489', ma003Id:'11620966164' },
  { num:'22224', name:'דרך השלום 105-117 ת"א',                               rawStatus:'Not Started',   budget:1643.33,ma004Id:'11572340990', ma003Id:'11620951524' },
  { num:'22225', name:'מרכז מסחרי יד מרדכי',                                 rawStatus:'Working on it', budget:200,    ma004Id:'11591518455', ma003Id:'11620980519' },
  { num:'22226', name:'התחדשות עירונית - טירת הכרמל',                        rawStatus:'Working on it', budget:3333.33,ma004Id:'11620721476', ma003Id:'11620973766' },
  { num:'22227', name:'אכסניית אנ"א מצפה רמון',                             rawStatus:'Working on it', budget:300.78, ma004Id:'11825725912', ma003Id:'11825979640' },
  { num:'22228', name:'מעלה אדומים מגרשים 312-313',                          rawStatus:'Working on it', budget:378.1,  ma004Id:'11923602281', ma003Id:'11949190059' },
  { num:'22229', name:'מעלה אדומים מגרשים 404-406',                          rawStatus:'Working on it', budget:533.9,  ma004Id:'11938288395', ma003Id:'11949197278' },
  { num:'22230', name:'איכילוב 4-16 מונטיפיורי 25 פ"ת',                    rawStatus:'Working on it', budget:587.53, ma004Id:'11937100764', ma003Id:'11947937099' },
  { num:'22231', name:'אכסניית אנ"א ערד',                                   rawStatus:'Working on it', budget:66.67,  ma004Id:'12096660012', ma003Id:null          },
  { num:'22232', name:'מעלה אדומים - ציפור מדבר מגרש 314',                  rawStatus:'Working on it', budget:700,    ma004Id:'12125433523', ma003Id:'12152784335' },
  // ── Done projects ──────────────────────────────────────────────────────────
  { num:'22106-1', name:'CUB1-UPW/Waste',                                    rawStatus:'DONE',          budget:21.3,   ma004Id:'8069174153',  ma003Id:null },
  { num:'22177',   name:'מתח"מ הטייסים',                                    rawStatus:'DONE',          budget:389.93, ma004Id:'9239596157',  ma003Id:null },
  { num:'22123',   name:'מגרש 61 אפקה קרית ביאליק',                         rawStatus:'DONE',          budget:663.3,  ma004Id:'7321609199',  ma003Id:null },
  { num:'22122',   name:'לגונה',                                              rawStatus:'DONE',          budget:658.8,  ma004Id:'7321609237',  ma003Id:null },
  { num:'22132',   name:'לבל - ליווי BIM משרדי',                            rawStatus:'DONE',          budget:300,    ma004Id:'11118514887', ma003Id:null },
  { num:'22139',   name:'סניט - ליווי BIM משרדי',                          rawStatus:'DONE',          budget:160,    ma004Id:'8235452672',  ma003Id:null },
  { num:'22142',   name:'פרויקט מרום 5-6',                                  rawStatus:'DONE',          budget:616.67, ma004Id:'7321609276',  ma003Id:null },
  { num:'22143',   name:'מגרש 22-23 קרית ביאליק',                           rawStatus:'DONE',          budget:411.79, ma004Id:'7321609282',  ma003Id:null },
  { num:'22148',   name:'קמפוס יהוד, מבנה 50',                              rawStatus:'DONE',          budget:133.33, ma004Id:'7638920023',  ma003Id:null },
  { num:'22149',   name:'האנגר',                                             rawStatus:'DONE',          budget:300,    ma004Id:'7718677252',  ma003Id:null },
  { num:'22152',   name:'בורוכוב 14 רעננה',                                 rawStatus:'DONE',          budget:200,    ma004Id:'7772411024',  ma003Id:null },
  { num:'22153',   name:'בורוכוב 24 רעננה',                                 rawStatus:'DONE',          budget:166.67, ma004Id:'7772411394',  ma003Id:null },
  { num:'22155',   name:'פרויקט 2016 - ביס מעון מתחם המשתלה',              rawStatus:'DONE',          budget:188.7,  ma004Id:'7941197282',  ma003Id:null },
  { num:'22137',   name:'רחובות ק. ההגנה',                                   rawStatus:'DONE',          budget:612,    ma004Id:'7321609218',  ma003Id:null },
  { num:'22160',   name:'בית לקוחות+מתחם תערוכות קבע',                     rawStatus:'DONE',          budget:120,    ma004Id:'8162690014',  ma003Id:null },
  { num:'22161',   name:'לפרויקט 923 במלמ תע"א',                           rawStatus:'DONE',          budget:166.67, ma004Id:'8219130556',  ma003Id:null },
  { num:'22167',   name:'הקוצר רמה"ש',                                      rawStatus:'DONE',          budget:257.26, ma004Id:'8545483434',  ma003Id:null },
  { num:'22202',   name:'ליווי BIM ארגוני - אנ"א',                         rawStatus:'DONE',          budget:100,    ma004Id:'10971882878', ma003Id:null },
]

// ── Load MA-003 lookup ─────────────────────────────────────────────────────

interface MA003Data { bimMgr: string; mep: string; modeller: string; accUrl: string }
const lookupPath = path.join(__dirname, '..', 'lib', 'ma003lookup.json')
const ma003Lookup: Record<string, MA003Data> = JSON.parse(fs.readFileSync(lookupPath, 'utf-8'))

function parseAccId(url: string): string | undefined {
  const m = url.match(/\/projects?\/([\w-]{8,})/)
  return m?.[1]
}

function toMember(name: string, mondayId?: string) {
  if (!name) return undefined
  return { name, mondayId: mondayId ?? undefined }
}

// ── Mongoose model (inline to avoid circular deps) ─────────────────────────

const SnapshotSchema = new mongoose.Schema({
  status:            { type: String, enum: ['Working on it','On Hold','Not Started','Done','Stuck'], default: null },
  milestoneProgress: { type: Number, default: null },
  hoursProgress:     { type: Number, default: null },
  budgetHours:       { type: Number, default: null },
  actualHours:       { type: Number, default: null },
  bimManager:        { type: Object, default: null },
  mepCoordinator:    { type: Object, default: null },
  bimModeller:       { type: Object, default: null },
  openIssuesCount:   { type: Number, default: null },
  accModelStatus:    { type: String, default: null },
  lastSyncedAt:      { type: Date,   default: null },
  syncStatus:        { type: String, default: 'ok' },
  mondayLastSyncedAt:{ type: Date,   default: null },
  sheetsLastSyncedAt:{ type: Date,   default: null },
  accLastSyncedAt:   { type: Date,   default: null },
}, { _id: false })

const ProjectSchema = new mongoose.Schema({
  projectName:   { type: String, required: true },
  projectNumber: { type: String, required: true },
  externalIds:   { type: Object, required: true },
  snapshot:      { type: SnapshotSchema, default: () => ({}) },
  isActive:      { type: Boolean, default: true },
  displayOrder:  Number,
}, { timestamps: true })

ProjectSchema.index({ projectNumber: 1 }, { unique: true })

const Project = mongoose.models.Project ?? mongoose.model('Project', ProjectSchema)

// ── Seed ───────────────────────────────────────────────────────────────────

async function seed() {
  await mongoose.connect(MONGODB_URI!)
  console.log('Connected to MongoDB')

  const now = new Date()
  let upserted = 0
  let errors   = 0

  for (let i = 0; i < MA004_PROJECTS.length; i++) {
    const p = MA004_PROJECTS[i]
    const ma003 = p.ma003Id ? (ma003Lookup[p.ma003Id] ?? null) : null
    const accUrl  = ma003?.accUrl || ''
    const accId   = accUrl ? parseAccId(accUrl) : undefined

    const snapshot = {
      status:             mapStatus(p.rawStatus),
      milestoneProgress:  null,
      hoursProgress:      null,   // TS-001 hours: will be added in Phase 3 sync
      budgetHours:        p.budget > 0 ? Math.round(p.budget * 100) / 100 : null,
      actualHours:        null,
      bimManager:         toMember(ma003?.bimMgr ?? ''),
      mepCoordinator:     toMember(ma003?.mep ?? ''),
      bimModeller:        toMember(ma003?.modeller ?? ''),
      openIssuesCount:    null,
      accModelStatus:     null,
      lastSyncedAt:       now,
      syncStatus:         'ok' as const,
      mondayLastSyncedAt: now,
      sheetsLastSyncedAt: null,
      accLastSyncedAt:    null,
    }

    const externalIds = {
      mondayBoardId:  MA004_BOARD_ID,
      mondayBoardUrl: MA004_BOARD_URL,
      mondayItemId:   p.ma004Id,
      ma003ItemId:    p.ma003Id ?? undefined,
      accProjectId:   accId,
      accProjectUrl:  accUrl || undefined,
    }

    try {
      await Project.findOneAndUpdate(
        { projectNumber: p.num },
        { $set: { projectName: p.name, isActive: true, externalIds, snapshot, displayOrder: i + 1 } },
        { upsert: true, new: true, runValidators: false }
      )
      upserted++
      process.stdout.write(`\r${upserted}/${MA004_PROJECTS.length} upserted`)
    } catch (err) {
      errors++
      console.error(`\nError on ${p.num}:`, err instanceof Error ? err.message : err)
    }
  }

  console.log(`\nDone. ${upserted} upserted, ${errors} errors.`)
  await mongoose.disconnect()
}

seed().catch(err => { console.error(err); process.exit(1) })
