import { createHash } from 'crypto'
import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { boardIdFromUrl, type MondayUpdate } from '@/lib/services/mondayService'
import { swrCache, cacheGet, cacheSet } from '@/lib/server/pageCache'
import {
  aggregateUpdates, updatesCacheKey, UPDATES_CACHE_TTL_MS, type UpdatesPayload,
} from '@/lib/server/updatesFeed'

// One-paragraph AI summary of a project's Monday updates feed, shown at the top
// of the Project Updates panel. The paragraph is generated by Claude from the
// same cached feed the panel renders (swrCache key `updates:{id}`), and is
// itself cached by a hash of the feed content — the model only runs again when
// an update or reply actually changed, not on every page view.

// Generating can take a few seconds; keep the Node runtime and allow time.
export const runtime = 'nodejs'
export const maxDuration = 60

// v2: prompt now excludes commercial/fee content — the version in the key
// invalidates every summary generated by the old prompt (the content hash
// alone wouldn't, since the feed itself didn't change).
const SUMMARY_KEY = (projectId: string) => `updates-summary:v2:${projectId}`

interface StoredSummary {
  summary: string
  inputHash: string
  generatedAt: string
}

// Content hash of the feed: any new update/reply or edited text changes it.
function feedHash(updates: MondayUpdate[]): string {
  const h = createHash('sha256')
  for (const u of updates) {
    h.update(`${u.id}|${u.createdAt}|${u.textBody.length}`)
    for (const r of u.replies) h.update(`${r.id}|${r.createdAt}|${r.textBody.length}`)
  }
  return h.digest('hex')
}

// Serialize the feed for the prompt, newest first, capped so the request stays
// small: the most recent updates carry the current status.
function feedText(updates: MondayUpdate[]): string {
  const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n)}…` : s)
  const date = (iso: string) => new Date(iso).toISOString().slice(0, 10)
  return updates.slice(0, 80).map(u => {
    const lines = [
      `[${date(u.createdAt)}] (${u.source.label}${u.source.itemName ? ` · ${u.source.itemName}` : ''}) ${u.creator.name ?? 'Unknown'}:`,
      clip(u.textBody.trim(), 600),
      ...u.replies.slice(0, 4).map(r =>
        `  ↳ [${date(r.createdAt)}] ${r.creator.name ?? 'Unknown'}: ${clip(r.textBody.trim(), 300)}`),
    ]
    return lines.filter(Boolean).join('\n')
  }).join('\n\n')
}

const SYSTEM_PROMPT =
  'You summarize the internal project-management update feed of a BIM (construction engineering) ' +
  'project for a project-status dashboard. Write exactly ONE cohesive paragraph of 3-6 sentences — ' +
  'no headings, no bullet points, no preamble — that gives a manager a clear picture of the ' +
  "project's current status: what is progressing, key decisions, open problems or blockers, and " +
  'what is expected next. Weigh recent updates much more heavily than old ones; ignore signatures, ' +
  'contact details and pleasantries. ' +
  'The summary is shown to ALL project employees, so commercial information is strictly off-limits: ' +
  'NEVER mention money or contract terms of any kind — fees (שכר טרחה / שכ"ט), prices, sums, budgets, ' +
  'hourly rates, payment terms, discounts, proposals or negotiations — even when the updates discuss ' +
  'them at length. Skip commercial updates entirely; an invoice/billing milestone (חשבון) may be ' +
  'mentioned only by its status (e.g. approved for submission), never with an amount. ' +
  'Focus on professional, technical, coordination and scheduling matters. ' +
  'Write in the language most of the updates are written in ' +
  '(Hebrew updates get a Hebrew summary). Mention people or dates only when they matter. ' +
  'Output only the paragraph.'

async function generateSummary(projectLabel: string, updates: MondayUpdate[]): Promise<string | null> {
  const client = new Anthropic()
  const response = await client.beta.messages.create({
    model: 'claude-opus-5',
    max_tokens: 2000,
    // Route refusals to a fallback model server-side instead of failing the panel.
    betas: ['server-side-fallback-2026-07-01'],
    fallbacks: 'default',
    system: SYSTEM_PROMPT,
    messages: [{
      role: 'user',
      content: `Project: ${projectLabel}\n\nUpdates feed (newest first):\n\n${feedText(updates)}`,
    }],
  })
  if (response.stop_reason === 'refusal') return null
  const text = response.content
    .filter((b): b is Anthropic.Beta.BetaTextBlock => b.type === 'text')
    .map(b => b.text).join('').trim()
  return text || null
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params

  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json({ summary: null, unavailable: true })
  }
  if (!process.env.MONGODB_URI || !process.env.MONDAY_API_TOKEN) {
    return NextResponse.json({ summary: null, unavailable: true })
  }

  try {
    const { connectDB } = await import('@easybim/db')
    const Project = (await import('@/app/models/Project')).default
    await connectDB()

    const doc = await Project.findById(id).lean() as Record<string, unknown> | null
    if (!doc) return NextResponse.json({ error: 'Project not found' }, { status: 404 })

    const ext = (doc.externalIds ?? {}) as Record<string, unknown>
    const masterItemId     = ext.mondayItemId as string | undefined
    const dedicatedBoardId = boardIdFromUrl(ext.dedicatedBoardUrl as string | undefined)

    // Same snapshot the panel just rendered — the client requests the summary
    // after the feed loaded, so this is virtually always a cache hit.
    const { data } = await swrCache<UpdatesPayload>(
      updatesCacheKey(id), UPDATES_CACHE_TTL_MS, false,
      () => aggregateUpdates(dedicatedBoardId, masterItemId),
    )
    const updates = data.updates
    if (updates.length === 0) return NextResponse.json({ summary: null, empty: true })

    const inputHash = feedHash(updates)
    const cached = await cacheGet<StoredSummary>(SUMMARY_KEY(id))
    if (cached && cached.inputHash === inputHash) {
      return NextResponse.json({ summary: cached.summary, generatedAt: cached.generatedAt })
    }

    const label = `${String(doc.projectNumber ?? '')} ${String(doc.projectName ?? '')}`.trim()
    let summary: string | null = null
    try {
      summary = await generateSummary(label, updates)
    } catch (err) {
      console.error('[updates-summary] generation failed:', err)
      // A stale summary beats no summary when the model call fails.
      if (cached) return NextResponse.json({ summary: cached.summary, generatedAt: cached.generatedAt, stale: true })
      return NextResponse.json({ summary: null, unavailable: true })
    }
    if (!summary) return NextResponse.json({ summary: null, unavailable: true })

    const stored: StoredSummary = { summary, inputHash, generatedAt: new Date().toISOString() }
    await cacheSet(SUMMARY_KEY(id), stored)
    return NextResponse.json({ summary, generatedAt: stored.generatedAt })
  } catch (err) {
    console.error('[GET /api/projects/[id]/updates-summary]', err)
    return NextResponse.json({ summary: null, unavailable: true })
  }
}
