import mongoose, { Schema, Document, Model } from 'mongoose'

// The bytes of a post cover — generated by Peacock, composed in BIM Composer,
// or uploaded by hand.
//
// Kept here rather than only on Drive because the service account is a member
// of exactly one shared drive (Finance) — "Marketing" is not visible to it, so
// the old upload-first flow failed outright and the post ended up with no image
// at all. Storing the bytes makes generation succeed on its own; the Drive copy
// is a best-effort archive layered on top (see peacock/posts.ts).
//
// A side collection rather than a field on the post: covers are ~1-2MB and the
// board lists 400 posts at a time, so they must never ride along on a post read.
// One image per post — regenerating replaces it.
export type PostImageOrigin = 'generated' | 'composer' | 'upload'

export const POST_IMAGE_ORIGINS: PostImageOrigin[] = ['generated', 'composer', 'upload']

export interface IPeacockImage extends Document {
  postId: string
  data: Buffer
  mimeType: string
  bytes: number
  prompt?: string // the post text the cover was generated from, for debugging
  driveUrl?: string // set once the Drive archive copy succeeds
  /**
   * Where the cover came from. Worth recording for the same reason a post has a
   * Source: "Peacock invented this" and "this is a render of a real EasyBIM
   * model" are very different claims to be making in a published post.
   */
  origin: PostImageOrigin
  /** For composer renders: the project the model belongs to. */
  projectNumber?: string
  /** Original filename for an upload, or the composer's export name. */
  fileName?: string
  createdAt: Date
  updatedAt: Date
}

const PeacockImageSchema = new Schema<IPeacockImage>(
  {
    postId: { type: String, required: true, unique: true, index: true },
    data: { type: Buffer, required: true },
    mimeType: { type: String, required: true },
    bytes: { type: Number, required: true },
    prompt: String,
    driveUrl: String,
    origin: { type: String, enum: POST_IMAGE_ORIGINS, default: 'generated' },
    projectNumber: String,
    fileName: String,
  },
  { timestamps: true }
)

const PeacockImage: Model<IPeacockImage> =
  mongoose.models.PeacockImage ??
  mongoose.model<IPeacockImage>('PeacockImage', PeacockImageSchema, 'peacock_images')

export default PeacockImage
