import type { ProjectRow } from './types'

const NEVER_SYNC: ProjectRow['sync'] = {
  lastSyncedAt: null,
  syncStatus: 'never',
  mondayLastSyncedAt: null,
  sheetsLastSyncedAt: null,
  accLastSyncedAt: null,
}

export const mockProjects: ProjectRow[] = [
  {
    _id: 'mock-22117',
    projectName: 'ספריית יהוד',
    projectNumber: '22117',
    displayOrder: 1,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22117',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22117',
      acc: 'https://acc.autodesk.com/projects/mock-22117',
    },
    status: 'On Hold',
    milestoneProgress: 65,
    hoursProgress: 65,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'דנה כהן', avatarUrl: undefined },
    mepCoordinator: { name: 'אורי לוי', avatarUrl: undefined },
    bimModeller: { name: 'מיכל ברק', avatarUrl: undefined },
    openIssuesCount: 3,
    accModelStatus: null,
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22121',
    projectName: 'ארנה הרצליה',
    projectNumber: '22121',
    displayOrder: 2,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22121',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22121',
      acc: 'https://acc.autodesk.com/projects/mock-22121',
    },
    status: 'On Hold',
    milestoneProgress: 65,
    hoursProgress: 65,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'יובל שרון', avatarUrl: undefined },
    mepCoordinator: { name: 'נועה פרץ', avatarUrl: undefined },
    bimModeller: { name: 'תום אבן', avatarUrl: undefined },
    openIssuesCount: 7,
    accModelStatus: null,
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22125',
    projectName: 'פרלבס פלאוס אוליפס',
    projectNumber: '22125',
    displayOrder: 3,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22125',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22125',
      acc: 'https://acc.autodesk.com/projects/mock-22125',
    },
    status: 'Working on it',
    milestoneProgress: 65,
    hoursProgress: 65,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'אדם גולן', avatarUrl: undefined },
    mepCoordinator: { name: 'שירה מזרחי', avatarUrl: undefined },
    bimModeller: { name: 'רון שפירא', avatarUrl: undefined },
    openIssuesCount: 12,
    accModelStatus: 'In Progress',
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22127',
    projectName: 'מגבת מזל שיבא',
    projectNumber: '22127',
    displayOrder: 4,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22127',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22127',
      acc: 'https://acc.autodesk.com/projects/mock-22127',
    },
    status: 'Not Started',
    milestoneProgress: null,
    hoursProgress: null,
    actualHours: null,
    budgetHours: null,
    bimManager: undefined,
    mepCoordinator: undefined,
    bimModeller: undefined,
    openIssuesCount: 0,
    accModelStatus: null,
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22128',
    projectName: 'פרויקט מול חנוך - מול הגליל',
    projectNumber: '22128',
    displayOrder: 5,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22128',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22128',
      acc: 'https://acc.autodesk.com/projects/mock-22128',
    },
    status: 'Working on it',
    milestoneProgress: 42,
    hoursProgress: 55,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'ליאת אורן', avatarUrl: undefined },
    mepCoordinator: { name: 'עידן כץ', avatarUrl: undefined },
    bimModeller: { name: 'שלי בן דוד', avatarUrl: undefined },
    openIssuesCount: 5,
    accModelStatus: 'In Progress',
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22129',
    projectName: 'ארנה אשדוד',
    projectNumber: '22129',
    displayOrder: 6,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22129',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22129',
      acc: 'https://acc.autodesk.com/projects/mock-22129',
    },
    status: 'Working on it',
    milestoneProgress: 78,
    hoursProgress: 70,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'גל אברהם', avatarUrl: undefined },
    mepCoordinator: { name: 'מור ישראלי', avatarUrl: undefined },
    bimModeller: { name: 'נתן צור', avatarUrl: undefined },
    openIssuesCount: 2,
    accModelStatus: 'Approved',
    sync: NEVER_SYNC,
  },
  {
    _id: 'mock-22130',
    projectName: 'נחמס כמה שמש',
    projectNumber: '22130',
    displayOrder: 7,
    links: {
      mondayBoard: 'https://easybim.monday.com/boards/22130',
      driveFolder: 'https://drive.google.com/drive/folders/mock-22130',
      acc: 'https://acc.autodesk.com/projects/mock-22130',
    },
    status: 'Stuck',
    milestoneProgress: 30,
    hoursProgress: 45,
    actualHours: null,
    budgetHours: null,
    bimManager: { name: 'יעל דרור', avatarUrl: undefined },
    mepCoordinator: undefined,
    bimModeller: { name: 'אסף קדם', avatarUrl: undefined },
    openIssuesCount: 18,
    accModelStatus: null,
    sync: NEVER_SYNC,
  },
]
